name: beh_minder
description: چالش نرم‌افزاری بهترینو - یادآور امور
#Developer: Hamed Prooshani

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^10.1.0
  get: ^4.6.1
  persian_number_utility: ^0.3.4
  persian_datetime_picker: ^2.4.0
  flutter_linear_datepicker: ^2.0.2
  shamsi_date: ^0.12.0
  mask_text_input_formatter: ^2.0.0
  blur: ^3.0.0
  provider: ^5.0.0
  ndialog: ^4.1.1
  glassmorphism: ^3.0.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: FarsiCinema
      fonts:
        - asset: fonts/Cinema Full.ttf

    - family: Traffic
      fonts:
        - asset: fonts/B Traffic-.ttf
        - asset: fonts/B Traffic Bold-.ttf
          weight: 600

    - family: Vazir
      fonts:
        - asset: fonts/Vazir-Medium-FD-WOL.ttf

    - family: Sahel
      fonts:
        - asset: fonts/Sahel-FD.ttf
        - asset: fonts/Sahel-VF.ttf

    - family: Monaco
      fonts:
        - asset: fonts/Monaco.ttf


